### ISSUE TITLE
Cannot start the application

### ISSUE THREAD

**Issue by ynott** [Ryoyo-NV/Gaze-Analysis-System#6]
# Environment:
  - HW: Jetson Xavier NX
  - OS: JetPack 4.6.1  

# Expected behaviour

I can run the application.

# Actual behaviour

I got the following error and could not start.

```
$ python3 run.py /dev/video0 --media v4l2 --cam-fps 10 
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from ds.ds_pipeline import DsVideo
  File "/home/t-yano/Projects/Gaze-Analysis-System/ds/ds_pipeline.py", line 20, in <module>
    import dscprobes
ImportError: libnvcv_faciallandmarks.so: cannot open shared object file: No such file or directory
```

# Step reprocedure.

1. Run upgrade
  `sudo apt upgrade`
3. Install Deepstream-6.0.1
  `sudo apt install -y deepstream-6.0`
4. Clone Git Repository & exec setup.sh
```shell
git clone https://github.com/Ryoyo-NV/Gaze-Analysis-System.git
git checkout -b jp4.6.2_ds6.0.1 refs/tags/jp4.6.2_ds6.0.1
chmod +x setup.sh
./setup.sh
```
The setup.sh shell has completed without any problems.
5. Start application

I have run the following

```
$ python3 run.py /dev/video0 --media v4l2 --cam-fps 10 
```

**Comment by ynott** [comment]
I found libnvcv_faciallandmarks.so in the following directory

```
$ ls -la /opt/nvidia/deepstream/deepstream/lib/cvcore_libs/libnvcv_faciallandmarks.so
-rw-r--r-- 1 root root 670856  2月 14 23:52 /opt/nvidia/deepstream/deepstream/lib/cvcore_libs/libnvcv_faciallandmarks.so
```

It appears to be linked from dscprobes.so

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/2724312/170638405-dc0a1006-8e00-4f6b-b4ad-78a14910decb.png">

**Comment by takutoi** [comment]
Do you set LD_LIBRARY_PATH?
https://github.com/Ryoyo-NV/Gaze-Analysis-System#usage
`export LD_LIBRARY_PATH=/opt/nvidia/deepstream/deepstream/lib/cvcore_libs:$LD_LIBRARY_PATH`

**Comment by ynott** [comment]
Oh!
I see!

This is my fault.
Thank you for your advice.
It worked!

close this issue.
