### ISSUE TITLE
[Request] Add LD_LIBRARY_PATH to .bashrc

### ISSUE THREAD

**Issue by ynott** [Ryoyo-NV/Gaze-Analysis-System#8]
I forget to set LD_LIBRARY_PATH every time.

I think I can just append the following to setup.sh ~/.bashrc.

```
export LD_LIBRARY_PATH=/opt/nvidia/deepstream/deepstream/lib/cvcore_libs:$LD_LIBRARY_PATH
```

You also might want to add the following entry to README.md.

- (optional) Add LD_LIBRARY_PATH to .bashrc

**Comment by takutoi** [comment]
Thank you for your suggention.
I added some comments to README.md.
